services:
  database:
    image: postgres
    container_name: database_convidados_casamento
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neondb
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api_server
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    
    
volumes:
  pgdata:
    driver: local
